title: Affiliation Extraction and Parsing from OpenALEX Preprints

directories:
  - assets
  - corpus
  - scripts

assets:
  - dest: "assets/preprints.csv"
    git:
      repo: https://github.com/sul-dlss-labs/preprints-evaluation-dataset.git
      branch: main
      path: records.csv
    checksum: 68138588160e22998f6e6921f4e705d8 # md5
    description: List of preprint documents in the training dataset

workflows:
  prepare:
    - preprints:download
    - preprints:clean
    - dataset:create

commands:
  - name: dependencies:install
    help: Install dependencies
    script:
      - pip install -r requirements.txt
      - python -m spacy download en_core_web_lg # for segmentation

  - name: preprints:download
    help: Download preprint PDFs
    outputs:
      - assets/preprints/pdf
    script:
      - python scripts/download_preprints.py assets/preprints.csv assets/preprints/pdf

  - name: preprints:clean
    help: Extract plain text from preprint PDFs
    deps:
      - assets/preprints/pdf
    outputs:
      - assets/preprints/txt
    script:
      - python scripts/clean_preprints.py assets/preprints/pdf assets/preprints/txt

  - name: dataset:create
    help: Create a dataset for annotating affiliations
    deps:
      - assets/preprints/txt
    outputs:
      - assets/datasets/preprints.jsonl
    script:
      - python scripts/create_dataset.py assets/preprints/txt assets/preprints.jsonl
