title: Affiliation Extraction and Parsing from OpenALEX Preprints

vars:
  embedding: "tok2vec" # tok2vec, transformer
  transformer_model_name: "roberta-base"
  gpu_id: -1
  config_file: "configs/config_${embedding}.cfg"

directories:
  - assets
  - training

assets:
  - dest: "assets/preprints.csv"
    git:
      repo: https://github.com/sul-dlss-labs/preprints-evaluation-dataset.git
      branch: main
      path: records.csv
    checksum: 68138588160e22998f6e6921f4e705d8 # md5
    description: List of preprint documents in the training dataset

workflows:
  prepare:
    - preprints:download
    - preprints:clean
    - dataset:create

commands:
  - name: dependencies:install
    help: Install dependencies
    script:
      - pip install -r requirements.txt
      - python -m spacy download en_core_web_lg # for suggestion & segmentation

  - name: preprints:download
    help: Download preprint PDFs (**Needs Stanford VPN**)
    outputs:
      - assets/preprints/pdf
    script:
      - python scripts/download_preprints.py assets/preprints.csv assets/preprints/pdf

  - name: preprints:clean
    help: Extract plain text from preprint PDFs
    deps:
      - assets/preprints/pdf
    outputs:
      - assets/preprints/txt
    script:
      - python scripts/clean_preprints.py assets/preprints/pdf assets/preprints/txt

  - name: dataset:create
    help: Create a dataset for annotating affiliations
    deps:
      - assets/preprints/txt
    outputs:
      - assets/datasets/preprints.jsonl
    script:
      - python scripts/create_dataset.py assets/preprints/txt assets/preprints.jsonl

  - name: annotate:ner
    help: Annotate training data for NER by correcting and updating an existing model
    deps:
      - assets/preprints.jsonl
    script:
      - python -m prodigy ner.correct preprints_ner en_core_web_lg assets/preprints.jsonl --label PERSON,ORG,GPE --update

  - name: annotate:spans
    help: Manually annotate training data for spans and relations
    deps:
      - assets/preprints.jsonl
    script:
      - python -m prodigy rel.manual preprints_spans en_core_web_lg assets/preprints.jsonl --label HAS --span-label AUTHOR,AFFILIATION --wrap

  - name: train
    help: Train spaCy pipeline for affiliation parsing
    deps:
      - "${vars.config_file}"
      - corpus/train.spacy
      - corpus/dev.spacy
    script:
      - "python -m spacy train ${config_file} --output training --gpu-id ${vars.gpu_id} --vars.transformer_model_name ${vars.transformer_model_name}"
