directories:
  - assets
  - corpus
  - scripts

assets:
  - dest: assets/dataset.zip
    checksum: 64491b27240100c462172a1074a1e931
    description: PDF dataset from SDR

commands:
  - name: dataset:unzip
    help: Unzip the training dataset
    script:
      - rm -rf assets/dataset
      - unzip assets/dataset.zip -d assets
      - rm -rf assets/__MACOSX
  - name: dataset:clean
    help: Extract plain text from PDFs in the training dataset
    script:
      - python scripts/clean_dataset.py assets/dataset assets/cleaned_dataset
